config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  get 'charges/create'
  get 'about' => 'welcome#about'
  
  devise_for :users
  
  resources :wikis
  
  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end
  
  resources :charges, only: [:new, :create]
  
  resources :users do
    member do
      post :downgrade
    end
  end
end  

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  enum role: [:standard, :premium, :admin]

  # Associations
  
  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :shared_wikis, through: :collaborators, source: :wiki
  
  # Validations
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  
  validates :name, 
    length: {minimum: 2, maximum: 100}, 
    presence: true
  
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false},
    length: { minimum: 3, maximum: 254},
    format: { with: VALID_EMAIL_REGEX }
  
  # Callbacks
  
  before_save { self.email = email.downcase if self.email.present? }
  
  
  # Instance Methods
  
  def collaborator?(wiki)
    self.collaborators.where(wiki: wiki).present?
  end

  def downgrade!
    ActiveRecord::Base.transaction do
      self.update_attribute(:role, :standard)
      self.wikis.where(private: true).all.each do |wiki|
        wiki.update_attribute(:private, false)
      end
    end
  end
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  
  default_scope { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if current_user.present?
      @user = params[:id] ? User.find(params[:id]) : current_user
    else
      redirect_to root_path
    end
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def downgrade
    @user = User.find(params[:id])
    @user.role = 'standard'

    if @user.save
      flash[:notice] = "You've been downgraded to standard. Your private wikis are now public."
      redirect_to :back
    else
      flash[:error] = "There was an error creating your account. Please try again."
      redirect_to :back
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!
  
  def index
    authorize(Wiki)
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @user = current_user
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @user = current_user
    
    @wiki = Wiki.new(user: current_user)
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    
    if @wiki.save
      flash[:notice] = "Wiki saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki has been updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error editing your Wiki. Please try again."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user_id, :user_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
    	options = {
      		filter_html:     true,
      		hard_wrap:       true,
      		link_attributes: { rel: 'nofollow', target: "_blank" },
      		space_after_headers: true,
      		fenced_code_blocks: true
    	}
  
    	extensions = {
      		autolink:           true,
      		superscript:        true,
      		disable_indented_code_blocks: true
    	}
  
    	renderer = Redcarpet::Render::HTML.new(options)
    	markdown = Redcarpet::Markdown.new(renderer, extensions)
  
    	markdown.render(text).html_safe
  	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/collaborators/_form.html.erb
<%= form_tag [wiki, collaborator] do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= submit_tag "Add User", class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <li><%= link_to "Users", users_path %></li>
      
      <div class="user-info pull-right">
      <% if user_signed_in? %>          
        <div class="pull-right">
          Hello, <strong><%= link_to current_user.name, user_path(current_user), :class => "navbar-link" %></strong> | 
          <%= link_to "Edit profile", edit_user_registration_path, :class => "navbar-link" %> -
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
            <p>
            <% if current_user.role == "standard" || current_user.role == "admin" %>
              <%= link_to "Upgrade to Premium", new_charge_path %>
            <% else %>
              <%= link_to "Downgrade to Standard", edit_user_registration_path %>
            <% end %>
            </p>
          </div>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => "navbar-link"  %> - 
        <%= link_to "Sign In", new_user_session_path, :class => "navbar-link"  %>
      <% end %>
  </ul>
  
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= yield %>
  </div>

 </body>
</html>

app/views/users/index.html.erb
<h1> Blocipedia Users </h1>

<div class="row">
  <div class="col-md-8">
    <% @users.each do |user| %>
      <div class="media">
        <div class="media-body">
          <p class="media-heading">
            <strong><%= user.name %></strong> (<%= user.role %>) <br>
            <a href="mailto:<%= user.email %>"><%= user.email %></a>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-md-8">
  <div class="media">
    <br />
    <div class="media-body">
      <h3 class="media-heading"><%= @user.name %></h3>
      <p>Account Type: <%= @user.role %></p>
      <p>Contributions: <%= pluralize(@user.wikis.count, 'wiki') %></p>
    </div>
  </div>
</div>
<hr />
<h3>WIKIS</h3>
  <%= render @user.wikis %>

app/views/welcome/about.html.erb
<h1>Welcome to Blocipedia!</h1>
<p>A project by Sergey Gorbatyuk</p>

app/views/welcome/index.html.erb
<br>

<div class="heading">
  <h1> Blocipedia</h1>

  <div class="box">
    <h3> Create and Share Wikis </h3>
    <p>
      <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %>
    </p>
  </div>
</div>


<div class="row">
  <div class="col-md-6">
    <h4 class="free-location"> Create Public Wikis </h4>
    <div class="free-button">
      <%= link_to "Free Plan", new_user_path, class: 'btn btn-info' %>
    </div>
  </div>

  <div class="col-md-5">
    <h4 class='premium-location'> Create Private Wikis </h4>
    <div class='premium-button'>
    <%= link_to "Premium Plan", new_charge_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>

  <% if @wiki.private %>
     <%= render partial: 'collaborators/form', locals: { f: f } %>
  <% end %>

  <%= f.submit "Save", class: 'btn btn-success' %>

<% end %>

app/views/wikis/_wiki.html.erb
<%= content_tag :div, class: 'media', id: "wiki-#{wiki.id}" do %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki_path(wiki) %>
      </h4>
      <small>
        submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %> <br>
      </small>
    </div>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Rules</p>
    <ul>
      <li>Keep it short.</li>
      <li>Stay on point.</li>
      <li>Be nice.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter New Wiki Title..." %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter New Wiki Body..." %>
      </div>
      <div>
        <%= f.label :private do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      </div>

      <div>
        <p>Add Collaborators</p>
        <% if current_user.id == @wiki.user_id || current_user.admin? %>
          <%= collection_check_boxes(:wiki, :user_ids, User.all, :id, :name) do |b| %>
            <%= b.check_box %>
            <%= b.label %><br />
          <% end %>
        <% end %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <% if wiki.private? %>
            <%= link_to markdown(wiki.title), wiki, class: "private" %> <small>[private]</small>
        <% else %>
            <%= link_to markdown(wiki.title), wiki %>
        <% end %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Rules</p>
    <ul>
      <li>Keep it short.</li>
      <li>Stay on point.</li>
      <li>Be nice.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki Title..." %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki Body..." %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Post", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>